apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hfbpbway5-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hfbpbway5-java-quarkus-gitops